apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Template generado para Previred, para el uso de Spring-Boot
    iconClass: icon-jboss
    version: '1.0'
  name: previred-spring-boot
labels:
  template: previred-spring-boot
parameters:
- name: APP_NAME
  displayName: Nombre Applicacion
  required: true
  value: SRV-
  description: Nombre de la aplicaci贸n.
- name: GIT_REPO
  displayName: URL repositorio Git
  value: https://github.com/GuillermoSaavedraBustos/restForum.git
  required: true
  description: La URL del repositorio.
- name: APP_VERSION
  displayName: Version aplicacion
  value: '1.0'
  required: true
  description: La Version de aplicacion.
- name: MAVEN_ARGS
  displayName: Argumentos Maven
  value: package -DskipTests -Dfabric8.skip -e -B
  description: Argumentos entregados a mvn en la construcci贸n de la aplicaci贸n.
- name: BUILD_SECRET
  displayName: Git Secret
  generate: expression
  description: El secret que se necesita para realizar el build.
  from: "[a-zA-Z0-9]{40}"
- name: CPU_REQUEST
  displayName: "% CPU utilizar "
  value: '0.2'
  required: true
  description: Cantidad CPU utilizar.
- name: CPU_LIMIT
  displayName: CPU limit
  value: '1.0'
  required: true
  description: El limite de CPU a utilizar.
- name: MEM_REQUEST
  displayName: "% MEMORIA utilizar"
  value: '0.1'
  required: true
  description: Cantidad MEMORIA utilizar.
- name: MEM_LIMIT
  displayName: MEMORIA limit
  value: 100M
  required: true
  description: El limite de MEMORIA a utilizar.
- name: JAVA_OPTIONS
  displayName: 'configuraci贸n  Memoria JVM '
  description: Limits for use to the JVM.
  value: "-Xmx100m -Xss256k -XX:MetaspaceSize=16m -XX:MaxMetaspaceSize=64m -XX:CompressedClassSpaceSize=32M
    -XX:ReservedCodeCacheSize=16M -XX:NativeMemoryTracking=summary -XX:MaxHeapFreeRatio=70"
  required: true
- name: ROUTE_URL
  displayName: URL servicio
  value: servicio-namespace
  description: La URL para consumir el servicio, debe existir dentor del wildcards.
- name: ROUTE_PATH
  displayName: Contexto del Servicio
  description: El contexto del servicio a consumir.
  value: "/"
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      component: "${APP_NAME}"
      provider: s2i
      project: "${APP_NAME}"
      version: "${APP_VERSION}"
      group: fis-java-springboot
    name: "${APP_NAME}-route"
  spec:
    host: "${ROUTE_URL}"
    path: "${ROUTE_PATH}"
    to:
      kind: Service
      name: "${APP_NAME}"
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      component: "${APP_NAME}"
      provider: s2i
      project: "${APP_NAME}"
      version: "${APP_VERSION}"
      group: fis-java-springboot
    name: "${APP_NAME}"
  spec:
    clusterIP: None
    deprecatedPublicIPs: []
    ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      project: "${APP_NAME}"
      component: "${APP_NAME}"
      provider: s2i
      group: fis-java-springboot
      version: "${APP_VERSION}"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp: 
    labels:
      component: "${APP_NAME}"
      group: fis-java-springboot
      project: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
  spec: {}
  status:
    dockerImageRepository: ''
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp: 
    labels:
      component: "${APP_NAME}"
      group: fis-java-springboot
      project: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
  spec:
    triggers:
    - type: GitHub
      github:
        secret: "${BUILD_SECRET}"
    - type: Generic
      generic:
        secret: "${BUILD_SECRET}"
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    source:
      type: Git
      git:
        uri: "${GIT_REPO}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: fis-java-openshift:2.0
        forcePull: true
        incremental: true
        env:
        - name: BUILD_LOGLEVEL
          value: '5'
        - name: MAVEN_ARGS
          value: "${MAVEN_ARGS}"
    output:
      to:
        kind: ImageStreamTag
        name: "${APP_NAME}:latest"
    resources: {}
  status:
    lastVersion: 0
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp: 
    labels:
      component: "${APP_NAME}"
      group: fis-java-springboot
      project: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
  spec:
    strategy:
      resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
    replicas: 1
    selector:
      component: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
      group: fis-java-springboot
      project: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
    template:
      metadata:
        creationTimestamp: 
        labels:
          component: "${APP_NAME}"
          deploymentconfig: "${APP_NAME}"
          group: fis-java-springboot
          project: "${APP_NAME}"
          provider: s2i
          version: "${APP_VERSION}"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: library/${APP_NAME}:latest
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 60
          ports:
          - containerPort: 8778
            name: jolokia
          - containerPort: 8888
            name: service
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_OPTIONS
            value: "${JAVA_OPTIONS}"
          resources:
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEM_REQUEST}"
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEM_LIMIT}"
  status: {}

